model_name: "../meta-llama/Qwen2.5-7B-Instruct"
reward_model_names: ["../meta-llama/Qwen2.5-7B-Instruct"]
model_device_map: {"main": "cuda:0", "reward0": "cuda:1"}
dataset: "hotpot_qa"
split: "train"
limit: 4000
output_dir: "data/trivia_qa/tqa_3000_qwen_generator_qwen_evaluator.jsonl"
n_generations: 10
batch_size: 4
